#!/usr/bin/env bash
# 兼容入口：VE 不再维护第二套 Python/CUDA 依赖，统一委托仓库根 setup_env.sh。
set -euo pipefail
VE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$VE_ROOT/.." && pwd)"

bash "$REPO_ROOT/setup_env.sh" "$@"
# shellcheck disable=SC1091
source "$REPO_ROOT/env.sh"

VE_OUT_BASE="${VE_OUT_BASE:-/root/autodl-tmp/ve}"
VE_MODEL_DIR="${VE_MODEL_DIR:-/root/autodl-tmp/ve_models}"
BEST_SEP_DIR="${BEST_SEP_DIR:-/root/autodl-tmp/pos_neg/best_sep}"
MODELSCOPE_CACHE="${MODELSCOPE_CACHE:-/root/autodl-tmp/cache/modelscope}"

cat >"$VE_ROOT/.env_ve" <<EOF
# generated by ve/setup_env.sh; Python/CUDA come from ../setup_env.sh
export VE_ROOT="$VE_ROOT"
export VE_OUT_BASE="$VE_OUT_BASE"
export PYTHON_BIN="$PYTHON_BIN"
export CLEARVOICE_PYTHON="$PYTHON_BIN"
export DAE_PYTHON_BIN="$PYTHON_BIN"
export VM_CONDA_ENV="${VM_CONDA_ENV:-ve-cu124}"
export PATH="$(dirname "$PYTHON_BIN"):\$PATH"
export VE_MODEL_DIR="$VE_MODEL_DIR"
export DATA_DIR="${DATA_DIR}"
export BEST_SEP_DIR="$BEST_SEP_DIR"
export HF_HOME="${HF_HOME:-/root/autodl-tmp/cache/huggingface}"
export TORCH_HOME="${TORCH_HOME:-/root/autodl-tmp/cache/torch}"
export MODELSCOPE_CACHE="$MODELSCOPE_CACHE"
export HF_ENDPOINT="\${HF_ENDPOINT:-https://hf-mirror.com}"
export OMP_NUM_THREADS="\${OMP_NUM_THREADS:-4}"
export MKL_NUM_THREADS="\${MKL_NUM_THREADS:-4}"
export PYTHONPATH="$VE_ROOT/scripts:${REPO_ROOT}/scripts:${REPO_ROOT}/VD/tools:${REPO_ROOT}/VM/scripts:\${PYTHONPATH:-}"
export PS4_WEIGHTS="\${PS4_WEIGHTS:-$VE_MODEL_DIR/PS4/checkpoint_epoch037.pt}"
export SPK_CHS_DIR="\${SPK_CHS_DIR:-$VE_MODEL_DIR/cnceleb_resnet34_LM}"
export ERES2NET_DIR="\${ERES2NET_DIR:-$VE_MODEL_DIR/eres2netv2_zh}"
export WESEP_ROOT="\${WESEP_ROOT:-$VE_MODEL_DIR/wesep}"
export MOSS_ONNX_PATH="\${MOSS_ONNX_PATH:-/root/autodl-tmp/checkpoints/MossFormer2_ONNX/simple_model.onnx}"
EOF

echo "[OK] VE 已绑定统一解释器: $PYTHON_BIN"
echo "source $VE_ROOT/.env_ve"
