#!/usr/bin/env bash
# 把大文件从系统盘迁到数据盘 /root/autodl-tmp，并在原路径留符号链接。
# 用法（建议先 dry-run）:
#   bash migrate_to_autodl_tmp.sh --dry-run
#   bash migrate_to_autodl_tmp.sh
#   bash migrate_to_autodl_tmp.sh --also-caches   # 额外迁 ~/.cache 等
set -euo pipefail

TMP="${AUTODL_TMP:-/root/autodl-tmp}"
DRY=0
ALSO_CACHES=0
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY=1; shift ;;
    --also-caches) ALSO_CACHES=1; shift ;;
    --force) FORCE=1; shift ;;
    --tmp) TMP="$2"; shift 2 ;;
    *) echo "未知参数: $1" >&2; exit 1 ;;
  esac
done

if [[ ! -d "$TMP" ]]; then
  echo "[ERR] 数据盘不存在: $TMP" >&2
  exit 1
fi

echo "============================================"
echo " migrate → $TMP"
echo " dry-run=$DRY  also-caches=$ALSO_CACHES"
echo "============================================"
df -h / "$TMP" 2>/dev/null || df -h /
echo ""

run() {
  if [[ "$DRY" == "1" ]]; then
    echo "[DRY] $*"
  else
    echo "[RUN] $*"
    eval "$@"
  fi
}

# 迁目录：src → $TMP/rel，再 ln -sfn 回 src
# 若 src 已是指向 TMP 的链接则跳过
migrate_one() {
  local src="$1"
  local rel="$2"   # 相对 TMP 的目标名，如 checkpoints / Qwen3-ASR-1.7B
  local dst="$TMP/$rel"

  if [[ ! -e "$src" && ! -L "$src" ]]; then
    echo "[SKIP] 不存在: $src"
    return 0
  fi

  if [[ -L "$src" ]]; then
    local cur
    cur="$(readlink -f "$src" 2>/dev/null || true)"
    if [[ "$cur" == "$dst" || "$cur" == "$(readlink -f "$dst" 2>/dev/null || true)" ]]; then
      echo "[OK ] 已是链接 → $src -> $cur"
      return 0
    fi
    echo "[WARN] $src 已是其它链接 → $(readlink "$src")，跳过（加 --force 可覆盖）"
    [[ "$FORCE" == "1" ]] || return 0
  fi

  # 已在数据盘上的真实目录
  local src_real
  src_real="$(readlink -f "$src" 2>/dev/null || echo "$src")"
  if [[ "$src_real" == "$TMP"/* ]]; then
    echo "[OK ] 已在数据盘: $src_real"
    return 0
  fi

  mkdir -p "$(dirname "$dst")"
  if [[ -e "$dst" || -L "$dst" ]]; then
    echo "[WARN] 目标已存在: $dst"
    if [[ "$FORCE" != "1" ]]; then
      echo "       若确认可合并/覆盖，加 --force 后重跑该项"
      # 仍可把 src 改成指向已有 dst
      if [[ ! -L "$src" ]]; then
        local bak="${src}.bak_sys_$(date +%Y%m%d%H%M%S)"
        run "mv '$src' '$bak'"
        run "ln -sfn '$dst' '$src'"
        echo "[OK ] $src -> $dst （原目录备份 $bak）"
      fi
      return 0
    fi
  fi

  if [[ -d "$src" && ! -L "$src" ]]; then
    run "mkdir -p '$TMP'"
    if [[ -d "$dst" ]]; then
      run "rsync -a --info=progress2 '$src/' '$dst/'"
      local bak="${src}.bak_sys_$(date +%Y%m%d%H%M%S)"
      run "mv '$src' '$bak'"
    else
      run "mv '$src' '$dst'"
    fi
    run "ln -sfn '$dst' '$src'"
    echo "[OK ] $src -> $dst"
  elif [[ -f "$src" && ! -L "$src" ]]; then
    run "mkdir -p '$(dirname "$dst")'"
    run "mv '$src' '$dst'"
    run "ln -sfn '$dst' '$src'"
    echo "[OK ] $src -> $dst"
  else
    echo "[SKIP] 无法处理: $src"
  fi
}

echo "---- 体积预览（系统盘常见大户）----"
du -sh \
  /root/checkpoints \
  /root/Qwen3-ASR-1.7B \
  /root/datasetA \
  /root/VM \
  /root/ClearerVoice-Studio \
  /root/miniconda3/envs \
  /root/.cache \
  /root/autodl-tmp/vm \
  2>/dev/null || true
echo ""

# 1) 分离权重、ASR、数据集、实验输出
migrate_one /root/checkpoints              checkpoints
migrate_one /root/Qwen3-ASR-1.7B           Qwen3-ASR-1.7B
migrate_one /root/datasetA                 datasetA

# 若实验输出误写在系统盘其它位置，可按需打开下一行
# migrate_one /root/vm_out                  vm

# 保证标准输出目录存在
run "mkdir -p '$TMP/vm'/{pos,neg,reports,packs,meta}"
run "mkdir -p '$TMP/checkpoints' '$TMP/cache'/{huggingface,torch,pip}"

# 2) 可选：pip / HF / torch 缓存 → 数据盘（省系统盘最多）
if [[ "$ALSO_CACHES" == "1" ]]; then
  migrate_one /root/.cache/huggingface     cache/huggingface
  migrate_one /root/.cache/torch           cache/torch
  migrate_one /root/.cache/pip             cache/pip
fi

# 3) 写环境片段，source 后路径与缓存都指向数据盘
ENV_SNIP="$TMP/env_paths.sh"
if [[ "$DRY" == "1" ]]; then
  echo "[DRY] 将写入 $ENV_SNIP"
else
  cat >"$ENV_SNIP" <<EOF
# generated by migrate_to_autodl_tmp.sh — source 此文件或并入 VM/env.sh
export AUTODL_TMP="$TMP"
export VM_OUT="\${VM_OUT:-$TMP/vm}"
export MOSS_CKPT_DIR="\${MOSS_CKPT_DIR:-$TMP/checkpoints}"
export ASR_MODEL_DIR="\${ASR_MODEL_DIR:-$TMP/Qwen3-ASR-1.7B}"
export DATA_DIR="\${DATA_DIR:-$TMP/datasetA}"
export HF_HOME="\${HF_HOME:-$TMP/cache/huggingface}"
# 勿再设 TRANSFORMERS_CACHE（transformers v5 已弃用，用 HF_HOME）
unset TRANSFORMERS_CACHE 2>/dev/null || true
export TORCH_HOME="\${TORCH_HOME:-$TMP/cache/torch}"
export PIP_CACHE_DIR="\${PIP_CACHE_DIR:-$TMP/cache/pip}"
export XDG_CACHE_HOME="\${XDG_CACHE_HOME:-$TMP/cache}"
mkdir -p "\$VM_OUT" "\$MOSS_CKPT_DIR" "\$HF_HOME" "\$TORCH_HOME" "\$PIP_CACHE_DIR"
EOF
  echo "[OK ] 写出 $ENV_SNIP"

  ROOT_VM="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  if [[ -d "$ROOT_VM" ]]; then
    mkdir -p "$ROOT_VM/.runtime"
    cp -f "$ENV_SNIP" "$ROOT_VM/.runtime/autodl_tmp_paths.sh"
    # 挂到 env.sh 末尾（幂等）
    if [[ -f "$ROOT_VM/env.sh" ]] && ! grep -q 'autodl_tmp_paths.sh' "$ROOT_VM/env.sh" 2>/dev/null; then
      echo "" >>"$ROOT_VM/env.sh"
      echo '# data-disk paths' >>"$ROOT_VM/env.sh"
      echo "[[ -f \"$ROOT_VM/.runtime/autodl_tmp_paths.sh\" ]] && source \"$ROOT_VM/.runtime/autodl_tmp_paths.sh\"" >>"$ROOT_VM/env.sh"
      echo "[OK ] 已挂到 $ROOT_VM/env.sh"
    fi
  fi
fi

echo ""
echo "---- 迁移后 ----"
df -h / "$TMP" 2>/dev/null || df -h /
echo ""
echo "建议:"
echo "  source $TMP/env_paths.sh"
echo "  # 或: cd /root/VM && source ./env.sh"
echo "  ls -la /root/checkpoints /root/Qwen3-ASR-1.7B /root/datasetA"
echo "  du -sh $TMP/* | sort -h"
echo ""
echo "若系统盘仍满，再跑:  bash $0 --also-caches"
echo "conda 环境很大时可手动:"
echo "  mv /root/miniconda3/envs/qwen3-asr $TMP/envs/qwen3-asr"
echo "  ln -sfn $TMP/envs/qwen3-asr /root/miniconda3/envs/qwen3-asr"
